### ISSUE TITLE
DX Does'nt initialize

### ISSUE THREAD

**Issue by velociraptor014** [dexyfex/CodeWalker#1]
![image](https://user-images.githubusercontent.com/34887918/34381932-f03584de-eb0b-11e7-8ffd-6c07a56dc887.png)

My GPU support Shader Model 5.0 without issues and it isn't an intagrated graphics...

I need to use CodeWalker but I cannot because i've this error everytime when starting the tool...

**Comment by dexyfex** [comment]
You wrote elsewhere that you solved this problem.
Generally, there's nothing I can do about this error, and it indicates that there is some compatibility problem with DX11 or your OS or drivers.

**Comment by Anfit5** [comment]
Need install update https://download.microsoft.com/download/1/4/9/14936FE9-4D16-4019-A093-5E00182609EB/Windows6.1-KB2670838-x64.msu
