### ISSUE TITLE
It crash instantly when loading the world

### ISSUE THREAD

**Issue by Fairswing** [dexyfex/CodeWalker#116]
CodeWalker load all the file and all the rpf archive really fast but when they are loaded and it start to load the world it freeze and then it crashes.
I attach the screenshot of the error taken from "CodeWalker error report tool"
![error](https://user-images.githubusercontent.com/79765241/126757697-3c7f0997-deba-412d-9163-fa56949bd5a0.PNG)

**Comment by StarkysDEV** [comment]
Did you resolve it?

**Comment by Fairswing** [comment]
Yes

Il lun 11 dic 2023, 01:23 St3rkysDEV ***@***.***> ha scritto:
