### ISSUE TITLE
[YTYP.XML Import] exteriorVisibiltyDepth does not stay -1 when importing

### ISSUE THREAD

**Issue by MoosheTV** [dexyfex/CodeWalker#139]
If I have an XML file with `exteriorVisibiltyDepth` set to `-1` under a `CMloRoomDef` child, it will set it back to `0`. This messes with how the exterior renders while inside the interior.

---
**Reproduction Steps**:
1. Export a `ytyp.xml` with an MLO with rooms defined, with `exteriorVisibiltyDepth` set to `-1`.
2. You can see that `exteriorVisibiltyDepth` is set to `-1` if you were to edit the `ytyp.xml` file in a text editor.
3. Re-import the `ytyp.xml`.
4. Edit the YTYP, and you can see that `exteriorVisibiltyDepth` is set back to `0`.

**Comment by dexyfex** [comment]
I followed the steps, and couldn't reproduce the problem. The exteriorVisibiltyDepth was correctly reimported as -1. Maybe you had a typo in that field name? Note the field name is supposed to be missing an i.

**Comment by MoosheTV** [comment]
My bad, this was a result of the typo missing in Sollumz, not CodeWalker's XML import. It was hard for me to notice it because of the typo 😅
