### ISSUE TITLE
No "Occlusion" option on Selection Tool in CodeWalker29

### ISSUE THREAD

**Issue by Kili2108** [dexyfex/CodeWalker#152]
I have no "Occlusion" option on Selection Tool in CodeWalker29.
I saw it on YouTube that there should be this option.

Youtube screenshot:
<img width="100" alt="image" src="https://user-images.githubusercontent.com/61068014/155866855-15f2db54-d66f-43a6-b2e3-ddab3cc83ac9.png">

My CodeWalker:
<img width="161" alt="image" src="https://user-images.githubusercontent.com/61068014/155866915-b35ced9f-1160-46fd-9cc9-71fbb8d4ccaa.png">

**Comment by katsutosh** [comment]
Hey,
Download the newest version from the Discord.
https://discord.gg/BxfKHkk

**Comment by Kili2108** [comment]
Thank you very much!
Now I have the option.
