### ISSUE TITLE
LOD Problem

### ISSUE THREAD

**Issue by RaketeOriginal** [dexyfex/CodeWalker#167]
Im using CodeWalker30_dev39 and everything was fine .. until i reinstalled GTAV .. now ive got a huge LOD problem in Codewalker. 
Its gone if im using the old version 29 .. but i need the features from v39

oh btw.. the lod is only there when i check DLC - but i cant work with DLC unchecked

can someone help me or send me the newest version?

![image](https://user-images.githubusercontent.com/110101558/181235535-65866487-140d-48c7-9b4c-8bc5bf764dab.png)

**Comment by RaketeOriginal** [comment]
![image](https://user-images.githubusercontent.com/110101558/181236359-b7b64514-93b4-499f-a6b5-59dfcde6f5d5.png)

**Comment by Disquse** [comment]
Verify game file and remove mods. Can't reproduce this.

**Comment by RaketeOriginal** [comment]
i will try .. but i dont use any mods in gtav, only on fivem

**Comment by RaketeOriginal** [comment]
no changes .. is there a version above CodeWalker30_dev39 i could try?

**Comment by RaketeOriginal** [comment]
Veryfied Game Files 
No Mods
The LOD Problem is only at the v39 and when i check the DLCs
I cant work with the old version and / or without mods 

So the LOD Problem must come from a DLC i guess ?!

**Comment by Disquse** [comment]
> So the LOD Problem must come from a DLC i guess ?!

Since this doesn't happen to other people, there has to be something in your game installation/cw installation/pc and etc that causes this.

**Comment by RaketeOriginal** [comment]
i tried everything .. no changes .. i dont get it ..

**Comment by RaketeOriginal** [comment]
Mayve the error console helps


update\update.rpf\dlc_patch\patchday1ng\x64\patch\data\lang\chinesesimp.rpf: System.Exception: Error in RPF7 file entry.
   bei CodeWalker.GameFiles.RpfBinaryFileEntry.Read(DataReader reader)
   bei CodeWalker.GameFiles.RpfFile.ReadHeader(BinaryReader br)
   bei CodeWalker.GameFiles.RpfFile.ScanStructure(BinaryReader br, Action`1 updateStatus, Action`1 errorLog)
   bei CodeWalker.GameFiles.RpfFile.ScanStructure(BinaryReader br, Action`1 updateStatus, Action`1 errorLog)
update\update.rpf\common\data\gta5_cache_y.dat: cache not loaded! Possibly an unsupported GTAV installation version.
x64f.rpf\levels\gta5\destruction\exterior\des_setpiece.rpf\des_setpiece.ytyp: ytyp file was not in meta format.
x64f.rpf\levels\gta5\destruction\interior\des_hosp_ceil.rpf\des_hosp_ceil.ytyp: ytyp file was not in meta format.
x64f.rpf\levels\gta5\destruction\interior\des_hosp_ceil2.rpf\des_hosp_ceil2.ytyp: ytyp file was not in meta format.
x64h.rpf\levels\gta5\interiors\v_int_14.rpf\v_int_14.ytyp: ytyp file was not in meta format.
x64j.rpf\levels\gta5\_citye\indust_02\id2_17.rpf\id2_17.ytyp: ytyp file was not in meta format.
x64q.rpf\levels\gta5\_hills\country_01\cs1_railwyc.rpf\cs1_railwyc.ytyp: ytyp file was not in meta format.

**Comment by RaketeOriginal** [comment]
problem solved .. v39 was buggy .. 44 got the fix for that
