### ISSUE TITLE
[Feature Request] RDR2 support?

### ISSUE THREAD

**Issue by JajarGaming** [dexyfex/CodeWalker#186]
I know this is a very hue feature request, but could we ever see this happening?

**Comment by DUZANUTO** [comment]
Codex is being developed for this

**Comment by JajarGaming** [comment]
> Codex is being developed for this

What's codex?

**Comment by Disquse** [comment]
Basically CodeWalker successor

**Comment by JajarGaming** [comment]
Yeah, I found it and subscribed to the Patreon
