### ISSUE TITLE
Error in RPF7 file entry.

### ISSUE THREAD

**Issue by aaron29th** [dexyfex/CodeWalker#26]
When ever I try to open this rpf with codewalker I get an error (see pic) which is odd as the file is unedited from rockstar and opens fine with openiv. Thanks
![image](https://user-images.githubusercontent.com/20888296/40514666-f079a834-5fa1-11e8-8c28-816df5c82587.png)

[rpf file.zip](https://github.com/dexyfex/CodeWalker/files/2037094/rpf.file.zip)

**Comment by neos7** [comment]
if you refer to the `update\update.rpf\dlc_patch\patchday1ng\x64\patch\data\lang\chinesesimp.rpf` that's normal

**Comment by dexyfex** [comment]
It's regarding the attached file? What did you use to create that RPF? Perhaps it was locked by openIV?

**Comment by aaron29th** [comment]
No it's straight from r* servers

**Comment by dexyfex** [comment]
?
CodeWalker is only designed to work with RPFs from GTAV game folder...

**Comment by aaron29th** [comment]
Ah I just assumed they were all the same like ps3 my bad

**Comment by dexyfex** [comment]
What do you mean all the same? Where is this file from exactly?

**Comment by aaron29th** [comment]
Its the background scripts rpf

**Comment by dexyfex** [comment]
Ah, well I guess more work is needed to support opening those.
