### ISSUE TITLE
[Feature Request] Add support for loading of DLC subPacks

### ISSUE THREAD

**Issue by neos7** [dexyfex/CodeWalker#31]
Some dlc packs allow to mount more than one rpf file, this seems to be used for the first time with the mpbattle dlc.
This is specified in the `setup2.xml` of the dlc itself by the node subPacksCount.
If `subPacksCount > 0` the root directory of the main dlc.rpf will also contains these dlc##.rpf starting with dlc1.rpf if `subPacksCount == 1` for example.
Although I don't know yet which is the limint of subPacks for each dlc.
Also it seems that the main dlc.rpf contains all the meta files and the content.xml to load everything from the virtual path (so even data which may be contained in subpacks) and subpacks are just used to exceed the limit of size of the rpf.

**Comment by dexyfex** [comment]
See if this (6e2c81675e5556cd9bbee2477cb1c53b37becd28) is doing what it's supposed to...

**Comment by neos7** [comment]
Seems to work fine
