### ISSUE TITLE
Corrupt Ytyp when saving in Project Window

### ISSUE THREAD

**Issue by calle-gunnarsson** [dexyfex/CodeWalker#36]
First of all, thanks for a great tool, especially the possibility to edit ytyp (I have a build of the master branch), but when I try to save an ytyp it seems to get corrupt, I've tried to create a new project, select an entity inside an interior/ytyp, I've choosen "Add to Project" in the Project Window, and the whole ytyp gets imported, so far so good, but if I save the ytyp without any modifications and try to load it in game the game crashes and OpenIV crashes when I try to open the new ytyp, I've noticed that the file size of the ytyp saved with codewalker is 21KB while the original is 23KB, I know using the latest and greatest from master isn't optimal and that ytyp modifications is experimental.

**Comment by dexyfex** [comment]
Thanks... What is the name of the .ytyp you're having this issue with?

**Comment by calle-gunnarsson** [comment]
The ytyp is  **v_int_2.ytyp**

**Comment by dexyfex** [comment]
Should be fixed with latest commit (cd9b54b3b8751c0097df295e15cb8cff8cf28693). Please test again, thanks!

**Comment by calle-gunnarsson** [comment]
I did a quick test this morning and it seems to work as expected, thank you for the fast update!
