### ISSUE TITLE
Move entity from one to another ymap

### ISSUE THREAD

**Issue by Djura2407** [dexyfex/CodeWalker#41]
Hello there, I am interested if there is possibilty to move Entity from one ymap to other ymap.
I am making maps and sometimes happens that I add entity to wrong ymap when I paste them, so I have to work from start then.
If that's possible I would like you to say me how to do it or if you could make it to be possible.

Thanks.

!!!!EDIT: What the fuck are eggs that you drop with CTRL+Left Mouse? 
I just don't understand it....

**Comment by dexyfex** [comment]
Eggs are for collisions testing.
You can move entities from one ymap to another via XML.
Extra entities editing functionality may be added to codewalker if I get the time.
