### ISSUE TITLE
Ymap not exporting certain rotation values

### ISSUE THREAD

**Issue by deadlykenny** [dexyfex/CodeWalker#50]
Not sure if this git is still monitored but I'm having issues with entities not storing the red rotation axis, basically both green and blue axis seem to work fine but when using the red one it doesn't make it in game and just flattens out the object, same with scale, that does not seem to save either

In codewalker: https://i.gyazo.com/814a6a71bd5ab5961403d3c4c0a81b16.jpg

Ingame: https://i.gyazo.com/cfcaa1146d67fec9a1e4ac1c14bfc77f.jpg

Any help would be appreciated

**Comment by dexyfex** [comment]
Use flag 1 (AllowFullRotation)

**Comment by farrukogangalee** [comment]
Hi, where do I find that option?
