### ISSUE TITLE
Feature request: Add JSON serlialization of ynd files

### ISSUE THREAD

**Issue by IanKirwan** [dexyfex/CodeWalker#75]
JSON serialization of the grid area ynd files would greatly aid folks working in the area of AI and driverless cars.  This data is important to developing navigation functions and creating datasets that could be used for machine learning based vehicle trajectory prediction. The data would be particularly  useful in JSON form as a lot of machine learning work is currently done in Python, and JSON->Python dictionaries is a doddle.

I believe the appropriate classes for this task are described here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/serialization/

CodeWalker.Core/GameFiles.FileTypes/YndFile.cs looks to be the place where ynd serialization should happen, though I don't know how this should tie into the GUI.

Unfortunately I'm not a c# programmer, otherwise I would just get on and do it. I suspect this is a really simple job for someone who knows what they are doing with c#.

I would be very grateful for this feature but will understand if it is a lot to ask. Many thanks nonetheless.

**Comment by carmineos** [comment]
You can already export ynd to xml and you easily translate that into json.

**Comment by IanKirwan** [comment]
Really? OK I havent found that feature. Thanks for the info. I'll see if I can get that to work.

**Comment by IanKirwan** [comment]
@carmineos Wasnt able to find how to do that. Perhaps I'm using the wrong version (29). What steps do you do to export ynd to xml? I can open my ynd files in the project tool but it will only allow me to save them as ynd files. There doesnt seem to an export facility. I guess I'm going to have to build the repo code right?

**Comment by carmineos** [comment]
Latest version should be `30_dev33`, unfortunately you have either to build it yourself or get it from the discord guild (artifacts might probably be available on github once the project will move entirely to .NET Core) 
Once you have latest version, simply select the .ynd file from the `RPF Explorer` and right click -> Export to XML
It should call [this](https://github.com/dexyfex/CodeWalker/blob/a510b9b37a8d0290f63d1bd5fc2119489221c904/CodeWalker.Core/GameFiles/FileTypes/YndFile.cs#L1329)

**Comment by IanKirwan** [comment]
Thanks @carmineos 
Much appreciated

**Comment by JayFoxRox** [comment]
Months have passed and this still didn't make it into a stable build.
I'm on Linux, so I can't just rebuild the codebase myself (GTA V works fine through Proton, and running CodeWalker through wine also works reasonably well).

Expecting people to register on Discord for builds isn't a great option either.
